-- Maintenance Records table for tracking maintenance work and costs
CREATE TABLE IF NOT EXISTS maintenance_records (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    owner_id INT UNSIGNED NOT NULL,
    property_id INT UNSIGNED DEFAULT NULL,
    house_id INT UNSIGNED DEFAULT NULL,
    tenant_id INT UNSIGNED DEFAULT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    category VARCHAR(100) DEFAULT 'General',
    priority ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium',
    status ENUM('pending', 'in-progress', 'completed', 'cancelled') DEFAULT 'pending',
    assigned_to VARCHAR(255) DEFAULT NULL,
    cost DECIMAL(12,2) DEFAULT 0.00,
    cost_notes TEXT DEFAULT NULL,
    vendor_name VARCHAR(255) DEFAULT NULL,
    vendor_phone VARCHAR(50) DEFAULT NULL,
    scheduled_date DATE DEFAULT NULL,
    completed_date DATE DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    recipient_type ENUM('individual', 'property', 'all') DEFAULT 'individual',
    recipient_ids TEXT DEFAULT NULL COMMENT 'JSON array of tenant IDs',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_maintenance_owner (owner_id),
    INDEX idx_maintenance_property (property_id),
    INDEX idx_maintenance_house (house_id),
    INDEX idx_maintenance_tenant (tenant_id),
    INDEX idx_maintenance_status (status),
    INDEX idx_maintenance_priority (priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;